export const FETCH_SEARCH_PLACES = 'FETCH_SEARCH_PLACES';
export const UPDATE_SEARCH_RESULTS = 'UPDATE_SEARCH_RESULTS';
export const FETCH_SEARCH_PLACES_FAILED = 'FETCH_SEARCH_PLACES_FAILED';
export const SHOW_SEARCH_OVERLAY = 'SHOW_SEARCH_OVERLAY';
export const HIDE_SEARCH_OVERLAY = 'HIDE_SEARCH_OVERLAY';
