export const FETCH_CURRENT_LOCATION_WEATHER = 'FETCH_CURRENT_LOCATION_WEATHER';
export const UPDATE_CURRENT_LOCATION_WEATHER = 'UPDATE_CURRENT_LOCATION_WEATHER';
export const FETCH_CURRENT_LOCATION_WEATHER_FAILED = 'FETCH_CURRENT_LOCATION_WEATHER_FAILED';
