export const INITIALIZE_APP = 'INITIALIZE_APP';
export const INITIALIZE_APP_SUCCESS = 'INITIALIZE_APP_SUCCESS';
export const INITIALIZE_APP_FAILED = 'INITIALIZE_APP_FAILED';
export const UPDATE_PLACES = 'UPDATE_PLACES';